version: '3.8'
services:
  auth-service:
    build: ./auth-service
    env_file: ./auth-service/.env
    ports:
      - "8081:8081"
    restart: unless-stopped

  leave-service:
    build: ./leave-service
    env_file: ./leave-service/.env
    ports:
      - "8082:8082"
    restart: unless-stopped

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - leave-service
    restart: unless-stopped 